### ISSUE TITLE
does api key really need to be PARAM_RAW?

### ISSUE THREAD

**Issue by danmarsden** [lmscloud-io/moodle-tool_vault#2]
https://github.com/lmscloud-io/moodle-tool_vault/blob/main/classes/form/apikey_form.php#L59 (and other locations)

can that be PARAM_TEXT instead?

**Comment by lmscloud-io** [comment]
Hi Dan. The problem with PARAM_TEXT is that it changes the user input without a warning. There is no security issue here because incorrect API key would not pass validation and will never be displayed back to the user. 

However I realised that I do not know what happens if the user is trying to enter some weird characters and I will just use it to sign the requests. Maybe it can break the headers.

So I left the type as PARAM_RAW_TRIMMED but added a validation that checks that the key is not too short, not too long and only contains letters and digits.

**Comment by danmarsden** [comment]
yeah - I agree - no security issue - I just try to make sure where PARAM_RAW is used that it makes sense and has been considered (which you have!) :-)

**Comment by lmscloud-io** [comment]
Thanks!
